env_vars:
  height: '186'
  weight: '76'
  flag: false


secret_env_vars: {}

web:

image:
  repository: null
  tag: latest  # Should be set by CI/CD
  pullPolicy: IfNotPresent

ingress:
  ipName: null
  hostnames: []
  tls:
    enabled: false
